# Generated by Django 3.2 on 2022-02-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videocall', '0003_alter_participant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='is_many',
            field=models.BooleanField(default=False),
        ),
    ]
