# Generated by Django 3.2 on 2022-02-13 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videocall', '0004_chatroom_is_many'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='is_many',
        ),
    ]
